spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    include: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true